
apiVersion: v1
kind: Service
metadata:
  name: nginx-chart
  labels:
    helm.sh/chart: nginx-chart-0.1.0
    app.kubernetes.io/name: nginx-chart
    app.kubernetes.io/instance: nginx-chart
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: nginx-chart
    app.kubernetes.io/instance: nginx-chart
